name: deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  KO_DOCKER_REPO: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ww24

jobs:
  publish_image:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      image_tag: ${{ steps.publish.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-gar@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      - uses: imjasonh/setup-ko@v0.5
      - name: Set env
        run: |
          echo "VERSION=$(echo "$GITHUB_REF" | awk -F'/' '{print $NF}')" >> $GITHUB_ENV
      - name: Publish container image
        id: publish
        run: |
          tag=$(echo "$VERSION" | awk -F'v' '{print $NF}')
          echo "::set-output name=image_tag::$tag"
          ko publish --preserve-import-paths --tags "$tag" .

  deploy:
    needs: [publish_image]
    permissions:
      contents: "read"
      pull-requests: "write"
      id-token: "write"
    uses: ww24/api-checker/.github/workflows/terraform.yml@master
    with:
      image_tag: ${{ needs.publish_image.outputs.image_tag }}
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
      REQUEST_BODY: ${{ secrets.REQUEST_BODY }}
      ENABLED: ${{ secrets.ENABLED }}
